version: '3.4'

services:
  user-migrate:
    build:
      dockerfile: Dockerfile.migrate
      context: .
    environment:
      DB_NAME: users
      DB_USER: user_svc
      DB_PASS: password
      DB_HOST: db
      DB_SSL_MODE: disable
    volumes:
      - "./migrations/user:/migrations"

  attendance-migrate:
    image: golang:1.13
    environment:
      DB_NAME: attendances
      DB_USER: attendance_svc
      DB_PASS: password
      DB_HOST: db
      DB_SSL_MODE: disable
    volumes:
      - "./migrations/attendance:/migrations"
