version: '3.1'

services:
  app:
    build:
      context: .
    environment:
      GIN_MODE: '${GIN_MODE:-debug}'
      DB_USER: '${DB_USER:-app}'
      DB_PASS: '${DB_PASS:-password}'
      DB_NAME: '${DB_NAME:-app_db}'
      DB_HOST: '${DB_HOST:-db}'
    ports:
      - '8080:${APP_PORT:-8080}'

  db:
    image: 'postgres:9.6.17'
    environment:
      POSTGRES_USER: '${DB_USER:-app}'
      POSTGRES_PASSWORD: '${DB_PASS:-password}'
      POSTGRES_DB: '${DB_NAME:-app_db}'
