FROM golang:1.13 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go mod verify


COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o attendance-server \
    github.com/nick96/cubapi/cmd/service/attendance

FROM scratch

WORKDIR /app

COPY --from=builder /app/attendance-server /app/attendance-server

ENTRYPOINT ["/app/attendance-server"]
