version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER:-app_user}
      POSTGRES_PASSWORD: ${PG_PASS:-password}
    volumes:
      - "/mnt/cubapi-db:/var/lib/postgresql/data"

  user:
    image: quay.io/nspain/user-service
    environment:
      DB_NAME: ${PG_NAME:-users}
      DB_USER: ${PG_USER:-user_svc}
      DB_PASS: ${PG_PASS:-password}
      DB_HOST: ${PG_HOST:-db}
      DB_SSL_MODE: disable
    labels:
      - "traefik.http.routers.user.rule=Host(`users.badgerer.space`)"
      - "traefik.http.routers.user.tls=true"
      - "traefik.http.routers.user.tls.certresolver=resolver"
      - "traefik.http.routers.user.tls.domains[0].main=badgerer.space"
      - "traefik.http.routers.user.tls.domains[0].sans=*.badgerer.space"

  # attendance:
  #   image: nick96/attendance-service
  #   environment:
  #     DB_NAME: ${PG_NAME:-attendance}
  #     DB_USER: ${PG_USER:-attendance_svc}
  #     DB_PASS: ${PG_PASS:-password}
  #     DB_HOST: ${PG_HOST:-db}
  #     DB_SSL_MODE: disable
  #   labels:
  #     - "traefik.http.routers.attendance.rule=Host(`attendance.badgerer.space`)"
  #     - "traefik.http.routers.attendance.tls=true"
  #     - "traefik.http.routers.attendance.tls.certresolver=resolver"
  #     - "traefik.http.routers.attendance.tls.domains[0].main=badgerer.space"
  #     - "traefik.http.routers.attendance.tls.domains[0].sans=*.badgerer.space"

  traefik:
    image: traefik:2.1
    command: |
      --providers.docker \
      --entryPoints.web.address=:80 \
      --entryPoints.websecure.address=:443 \
      --certificatesResolvers.resolver.acme.email=nicholas.spain96@gmail.com \
      --certificatesResolvers.resolver.acme.sorage=acme.json
      --certificatesResolvers.resolver.acme.httpChallenge.entryPoint=web
      
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
