version: '3.4'

services:
  user:
    build:
      dockerfile: Dockerfile.reflex
      context: .
    volumes:
      - ./:/app
    command: -g '**/*.go' -g 'go.mod' -s go run github.com/nick96/cubapi/cmd/service/user

  attendance:
    build:
      dockerfile: Dockerfile.reflex
      context: .
    volumes:
      - ./:/app
    command: -g '**/*.go' -g 'go.mod' -s go run github.com/nick96/cubapi/cmd/service/attendance
