FROM golang:1.14 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
RUN go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -ldflags="-w -s" -o /app/autocrat github.com/nick96/cubapi/cmd/autocrat

FROM scratch

WORKDIR /app
COPY --from=builder /app/autocrat /app/autocrat
cmd ["/app/autocrat"]
